name: 🔍 Debug Server Status

on:
  workflow_dispatch:  # Manual trigger only

env:
  VPS_HOST: 104.168.159.24
  VPS_PORT: 57411
  VPS_USER: deploy
  DEPLOY_PATH: /opt/lanet-helpdesk

jobs:
  debug-server:
    name: 🔍 Check Server Status
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🔐 Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p ${{ env.VPS_PORT }} ${{ env.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: 🧪 Test SSH Connection
        run: |
          ssh -i ~/.ssh/id_ed25519 -p ${{ env.VPS_PORT }} ${{ env.VPS_USER }}@${{ env.VPS_HOST }} "echo 'SSH connection successful'"

      - name: 🔍 Run Server Diagnostics
        run: |
          ssh -i ~/.ssh/id_ed25519 -p ${{ env.VPS_PORT }} ${{ env.VPS_USER }}@${{ env.VPS_HOST }} << 'EOF'
            set -e
            
            echo "🔍 CHECKING LANET HELPDESK SERVER STATUS..."
            echo "================================================"
            
            # Check Docker containers status
            echo "📦 Docker Containers Status:"
            docker ps -a
            
            echo ""
            echo "🌐 Network Status:"
            sudo netstat -tlnp | grep -E ':(80|443|5001|5173|5432|6379)' || echo "No services on expected ports"
            
            echo ""
            echo "📋 Container Logs (last 10 lines each):"
            
            echo "--- Frontend Logs ---"
            docker logs --tail=10 lanet-helpdesk-frontend 2>&1 || echo "Frontend container not found"
            
            echo ""
            echo "--- Backend Logs ---"
            docker logs --tail=10 lanet-helpdesk-backend 2>&1 || echo "Backend container not found"
            
            echo ""
            echo "--- PostgreSQL Logs ---"
            docker logs --tail=10 lanet-helpdesk-postgres 2>&1 || echo "PostgreSQL container not found"
            
            echo ""
            echo "--- Redis Logs ---"
            docker logs --tail=10 lanet-helpdesk-redis 2>&1 || echo "Redis container not found"
            
            echo ""
            echo "🔧 System Resources:"
            df -h / || true
            free -h || true
            
            echo ""
            echo "🌍 External Connectivity Test:"
            curl -I http://localhost:80 2>&1 || echo "Port 80 not responding"
            curl -I http://localhost:5001/api/health 2>&1 || echo "Backend API not responding"
            
            echo ""
            echo "📊 Docker Compose Status:"
            cd /opt/lanet-helpdesk
            docker-compose ps 2>&1 || echo "Docker compose not found"
            
            echo ""
            echo "🔍 Process Status:"
            ps aux | grep -E '(docker|nginx)' | grep -v grep || echo "No docker/nginx processes"
            
            echo "================================================"
            echo "✅ Server status check completed!"
          EOF
